import type { StageConfig } from '../types'

export const stageConfigs: StageConfig[] = [
  {
    id: 1,
    name: 'Tutorial',
    duration: 60,
    gameSpeed: 1.0,
    backgroundColor: 0x87ceeb,
    groundColor: 0x2e8b57,
    ceiling: false,
    boss: 'BOSS1',
    spawn: {
      hasEnemies: true,
      enemyTypes: ['A', 'B', 'C'],
      obstacleTypes: ['grass', 'tree'],
      enemyInterval: 2.5,
      obstacleInterval: 5,
      allowEnemyBullets: false,
    },
  },
  {
    id: 2,
    name: 'Speed Up',
    duration: 90,
    gameSpeed: 1.5,
    backgroundColor: 0xff6347,
    groundColor: 0xffa500,
    ceiling: false,
    boss: 'BOSS2',
    spawn: {
      hasEnemies: true,
      enemyTypes: ['A', 'B', 'C', 'D'],
      obstacleTypes: ['rock', 'pillar'],
      enemyInterval: 2.2,
      obstacleInterval: 4.5,
      allowEnemyBullets: true,
    },
  },
  {
    id: 3,
    name: 'High Speed & Ceiling',
    duration: 90,
    gameSpeed: 4.0,
    backgroundColor: 0x9370db,
    groundColor: 0xff00ff,
    ceilingColor: 0x0000ff,
    ceiling: true,
    boss: 'BOSS3',
    spawn: {
      hasEnemies: false,
      enemyTypes: [],
      obstacleTypes: ['pillar', 'board'],
      enemyInterval: 999,
      obstacleInterval: 2.0,
      allowEnemyBullets: false,
    },
  },
  {
    id: 4,
    name: 'Mid-Boss',
    duration: 120,
    gameSpeed: 1.0,
    backgroundColor: 0xff1493,
    groundColor: 0xff0000,
    ceiling: false,
    boss: 'BOSS4',
    midBoss: 'BOSS4H',
    spawn: {
      hasEnemies: true,
      enemyTypes: ['A', 'B', 'C', 'D', 'E'],
      obstacleTypes: ['rock', 'pillar', 'tree', 'grass'],
      enemyInterval: 1.8,
      obstacleInterval: 3.2,
      allowEnemyBullets: false,
    },
  },
  {
    id: 5,
    name: 'Final',
    duration: 120,
    gameSpeed: 2.5,
    backgroundColor: 0x000080,
    groundColor: 0x0000ff,
    ceilingColor: 0xffff00,
    ceiling: true,
    boss: 'BOSS5',
    midBoss: 'BOSS5H',
    spawn: {
      hasEnemies: true,
      enemyTypes: ['A', 'B', 'C', 'D', 'E', 'F'],
      obstacleTypes: ['rock', 'pillar', 'tree', 'grass', 'board'],
      enemyInterval: 1.5,
      obstacleInterval: 2.5,
      allowEnemyBullets: true,
    },
  },
]
